### PR TITLE
fix(namespaces): api.namespaces('foo') usage

### LINKED ISSUE #187: Fetch a specific namespace
Currently, the following yields every namespace:

```js
core.namespaces('mynamespace').get((err, data) => {
  // data contains every namespace
})
```

I can't seem to find the recommended method of searching for a specific namespace using the following API endpoint: `/api/v1/namespaces/mynamespace`

Thoughts @silasbw? Thanks in advance.

### PR DESCRIPTION
**Pull request by silasbw**
Fixes #187

BREAKING CHANGE: Removes default namespace feature. With a default namespace,
`api.namespaces.get` is potentially ambiguous: get the default namespaces or
get all namespaces. Remove the default namespace to be consistent with other
code.

### CODE REVIEW

**Comment by austinkelleher** [comment]
Thanks for getting this fix out quickly @silasbw. Really appreciate it. I've tested your fix and it works great. Do you have plans to publish a new version soon? Thanks again.

**Comment by silasbw** [comment]
Hey @austinkelleher .  I'm trying to get the major release out today or tomorrow.  There's one other thing I want to include.  I'm putting the PRs together now.  I'll update https://github.com/godaddy/kubernetes-client/issues/187 when we publish to npm.

**Comment by silasbw** [comment]
@austinkelleher, I just published 4.0.0 to npm.  Thanks for testing this change out.

**Comment by austinkelleher** [comment]
Everything is working great on 4.0.0 @silasbw. Thanks again for the quick fix.

**Pull request merged**
