### PR TITLE
feat(CRDs): add Cluster scope support

### PR DESCRIPTION
**Pull request by popomore**
Ref https://github.com/godaddy/kubernetes-client/issues/215

### CODE REVIEW

**Comment by popomore** [comment]
https://travis-ci.org/godaddy/kubernetes-client/jobs/412672463

It seems travis make the test failed.

**Comment by popomore** [comment]
@silasbw This feature is required by us, can you review and publish a new version?

**Comment by silasbw** [comment]
Looking!

**Comment by silasbw** [comment]
I just published kubernetes-client@5.4.0 which includes this.

**Pull request merged**
