### PR TITLE
Add quick fix for 403 throws on pod-exec

### PR DESCRIPTION
**Pull request by Antoninbln**
## Purpose 
Exec request throws 403 error.
Exec failing route : `api.v1.namespaces(NAMESPACE).pods(PODNAME).exec.post()`.

## Problem identification
`ws` seems to only supports authorization header for token authentication which is not passed to `ws` instance. Please see this [answer](https://github.com/godaddy/kubernetes-client/issues/346#issuecomment-489602443) for more details.

The [issue](https://github.com/godaddy/kubernetes-client/issues/346#issuecomment-489602443).

I hope it helps :)

### CODE REVIEW

**Comment by Stono** [comment]
Could we get this merged if possible?  It's a real blocker for me!

**Comment by jBouyoud** [comment]
@silasbw, Seems to break something else. 
Since the version 8.3.5, I got `Failed to get /openapi/v2 and /swagger.json: Unauthorized`... 
Rollback to 8.3.4 fix the issue. 
I investigate why.

**Comment by silasbw** [comment]
Ah bummer, thanks for looking into it.

**Comment by Stono** [comment]
Aye this is broken on 8,.3.5

**Pull request merged**
