### PR TITLE
Fixed promises problem with Typings.

### PR DESCRIPTION
**Pull request by nagapavan**
Fixes issue #249

### CODE REVIEW

**Comment by nagapavan** [comment]
These changes are little different from #183 
Please review and check-in.

**Comment by nagapavan** [comment]
@silasbw Can you please review and merge this PR?

**Comment by NoChance777** [comment]
+1 can't use 5.2.0 without appropriate typings

**Comment by silasbw** [comment]
Sure, but we'll need https://github.com/godaddy/kubernetes-client/issues/249 for the 5.X+ interface.

**Pull request merged**
